document.writeln("<!DOCTYPE html PUBLIC \'-//W3C//DTD XHTML 1.0 Transitional//EN\' \'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\'>");
document.writeln("<html xmlns=\'http://www.w3.org/1999/xhtml\'>");
document.writeln("<head>");
document.writeln("<style>");
document.writeln("</style>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />");
document.writeln("<title></title>");
document.writeln(" <link href=\'head.css\'  rel=\'stylesheet\' type=\'text/css\' />");
document.writeln("</head>");
document.writeln("<body >");
document.writeln(" <div class=\'miaov_head\'>");
document.writeln("    <ul>");
document.writeln("      <li><a href=\'http://www.cnblogs.com/jtjds/\'>Mac</a></li>");
document.writeln("      <li><a href=\'http://www.cnblogs.com/jtjds/\'>iPad</a></li>");
document.writeln("      <li><a href=\'http://www.cnblogs.com/jtjds/\'>iPhone</a></li>");
document.writeln("      <li><a href=\'http://www.cnblogs.com/jtjds/\'>Watch</a></li>");
document.writeln("      <li><a href=\'http://www.cnblogs.com/jtjds/\'>Music</a></li>");
document.writeln("      <li><a href=\'http://www.cnblogs.com/jtjds/\'>Contact Us</a></li>");
document.writeln("    </ul>");
document.writeln("</div>");
document.writeln(" ");
document.writeln("</body>");
document.writeln("</html>");